{% set name = "augment-nd" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/augment-nd-{{ version }}.tar.gz
  sha256: 198ea2d9d95fbed0a7763c30e7ad098a82be906ab97902f863253d94f01c2da5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - h5py
    - numpy
    - python >=3.6
    - scipy

test:
  imports:
    - augment
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/funkey/augment
  summary: Simple elastic augmentation for ND arrays.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
